---
PATH: ""
TLS_CERT_PATH: ""
TLS_KEY_PATH: ""
STATIC_ASSETS_DIR: ""
CREDENTIALS_TCPPORT: ""
CREDENTIALS_URI:  
SMTP_SERVER: 
SMTP_ACCOUNT: 
SMTP_PASSWORD: 
STORAGE_ROOT: 
STORAGE_TCPPORT: 
STORAGE_URI: 
TTYD_HOST_CONSOLE_PORT: "" 
TTYD_EM100_BIOS_PORT: ""
TTYD_EM100_BMC_PORT: ""
TTYD_OS_LOADER: ""
CTRL_IP: 
EXPECT_BMC_IP: 
BCC_ADDRESS: 
COMPILE_URI: 
COMPILE_TCPPORT: "" 
MAX_SERVER_AGE:
